// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  articleContent: string;
  articleDetails: string;
}
export const cssExports: CssExports;
export default cssExports;
