export const GET_ARTICLES = 'GET_ARTICLES';
export const REQUEST_ARTICLES = 'REQUEST_ARTICLES';
export const RECEIVE_ARTICLES = 'RECEIVE_ARTICLES';
export const FAIL_ARTICLE_REQUEST = 'FAIL_ARTICLE_REQUEST';
