// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'date': string;
  'form': string;
  'line': string;
  'pagination': string;
}
export const cssExports: CssExports;
export default cssExports;
