// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'Button': string;
  'female': string;
  'male': string;
  'primary': string;
}
export const cssExports: CssExports;
export default cssExports;
